name: Build container images

on:
  push:
    paths:
      - "*/Dockerfile"
  workflow_dispatch:
    inputs:
      apps:
        description: "Comma-separated list of applications to build (e.g., caddy,patroni)"
        required: false

permissions:
  contents: read
  packages: write

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      apps_to_build: ${{ steps.detect.outputs.apps_to_build }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Fetch the current and previous commit to ensure `github.event.before` is available
          fetch-depth: 2

      - name: Detect Applications to Build
        id: detect
        run: |
          bash .github/scripts/detect_apps.sh "${{ github.event.inputs.apps }}" "${{ github.event.before }}" "${{ github.sha }}"
        env:
          GITHUB_OUTPUT: $GITHUB_OUTPUT

  build:
    needs: detect
    runs-on: ubuntu-latest
    if: ${{ needs.detect.outputs.apps_to_build != '' && needs.detect.outputs.apps_to_build != 'No apps detected.' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to ghcr.io
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Images
        run: |
          bash .github/scripts/build_and_push.sh "${{ needs.detect.outputs.apps_to_build }}"
